### ISSUE TITLE
PaperEditPage 구현

### ISSUE THREAD

**Issue by sihyonn** [sihyonn/sprint-part2-rollingProject#70]
## 📌 기능설명
post/id/edit에 해당하는 카드 메시지 수정 페이지 작업

![6B186370-73BE-470D-8234-8CCF39EDAD1D](https://github.com/sihyonn/sprint-part2-rollingProject/assets/124874266/1559c261-ae0c-4bbf-a8ee-1d239ca7e366)

## 📌 ToDo
- [x] UI
- [ ] API

## 🤔 ETC[선택]
편집 후 확인 버튼을 누르면 일반 PaperViewerPage로 이동해야할까요..? 
뭐랄까 피그마 시안만보면 편집이 종료되어 돌아가는 지점이없달까?

**Comment by ggjiny** [comment]
롤링페이퍼 삭제하면 메인으로 가고 카드 삭제하면 그 자리에 있어도 괜찮을거 같아요~ 
어차피 삭제하러 가는 이동은 url로 밖에 못하니까.. ?? ..

**Comment by sihyonn** [comment]
그 자리에 있는게 편집페이지? 아니면 Paper보는페이지?

**Comment by ggjiny** [comment]
편집 페이지!
